### ISSUE TITLE
Can you please check if the Cheeseswap pair address link is correct?

### ISSUE THREAD

**Issue by citypayorg** [cheeseswapbsc/cheeseswap-interface#13]
Token Name: GGB Token
Token Ticker: GGB
Token Type: BEP20
Token Decimal: 18
Explorer Link: https://bscscan.com/address/0x368aB5E3330746974a8e221F29ef8a71eC074242
256px Logo link: https://github.com/ggbbest/ggb/raw/main/ggb256.png
Cheeseswap pair address link: https://bscscan.com/address/0xadd8a06fd58761a5047426e160b2b88ad3b9d464

**Comment by blockartist** [comment]
No. You have to give your token pair link, at least one.
