### ISSUE TITLE
Litherium(LITH)

### ISSUE THREAD

**Issue by 0xBenxx211226** [cheeseswapbsc/cheeseswap-interface#15]
Token Name: Litherium Token
Token Ticker: LITH
Token Type: BEP20
Token Decimal: 18
Explorer Link: https://bscscan.com/address/0x5b180109332b079c44447f52a8adad5b1cd9dcfd
256px Logo link: https://www.my-lith.com/LOGO.png
Cheeseswap pair address link: https://info.cheeseswap.app/?_gl=1*fd8b8*_ga*NTQ1NTE4NDQ5LjE2MzM0MjQ5NDU.*_ga_SJBC5SKP7Q*MTYzMzQyNDk0NC4xLjAuMTYzMzQyNDk0Ni4w#/pair/0x9155179f06deea129c2a4353bc0b791c548c7da0

**Comment by blockartist** [comment]
Listed.
